//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApplication.BookshopServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/BookshopService")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string guidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string guid {
            get {
                return this.guidField;
            }
            set {
                if ((object.ReferenceEquals(this.guidField, value) != true)) {
                    this.guidField = value;
                    this.RaisePropertyChanged("guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnsuccessfullLoginFault", Namespace="http://schemas.datacontract.org/2004/07/BookshopDatabase")]
    [System.SerializableAttribute()]
    public partial class UnsuccessfullLoginFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookModel", Namespace="http://schemas.datacontract.org/2004/07/BookshopDatabase")]
    [System.SerializableAttribute()]
    public partial class BookModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiscountPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InstockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsbnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublicationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiscountPrice {
            get {
                return this.DiscountPriceField;
            }
            set {
                if ((this.DiscountPriceField.Equals(value) != true)) {
                    this.DiscountPriceField = value;
                    this.RaisePropertyChanged("DiscountPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Instock {
            get {
                return this.InstockField;
            }
            set {
                if ((this.InstockField.Equals(value) != true)) {
                    this.InstockField = value;
                    this.RaisePropertyChanged("Instock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Isbn {
            get {
                return this.IsbnField;
            }
            set {
                if ((object.ReferenceEquals(this.IsbnField, value) != true)) {
                    this.IsbnField = value;
                    this.RaisePropertyChanged("Isbn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PublicationDate {
            get {
                return this.PublicationDateField;
            }
            set {
                if ((object.ReferenceEquals(this.PublicationDateField, value) != true)) {
                    this.PublicationDateField = value;
                    this.RaisePropertyChanged("PublicationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArgumentFault", Namespace="http://schemas.datacontract.org/2004/07/BookshopDatabase")]
    [System.SerializableAttribute()]
    public partial class ArgumentFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArgumentNullFault", Namespace="http://schemas.datacontract.org/2004/07/BookshopDatabase")]
    [System.SerializableAttribute()]
    public partial class ArgumentNullFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IndexOutOfRangeFault", Namespace="http://schemas.datacontract.org/2004/07/BookshopDatabase")]
    [System.SerializableAttribute()]
    public partial class IndexOutOfRangeFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookshopServiceReference.IMyBookshopService")]
    public interface IMyBookshopService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyBookshopService/Login", ReplyAction="http://tempuri.org/IMyBookshopService/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientApplication.BookshopServiceReference.UnsuccessfullLoginFault), Action="http://tempuri.org/IMyBookshopService/LoginUnsuccessfullLoginFaultFault", Name="UnsuccessfullLoginFault", Namespace="http://schemas.datacontract.org/2004/07/BookshopDatabase")]
        ClientApplication.BookshopServiceReference.User Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyBookshopService/Login", ReplyAction="http://tempuri.org/IMyBookshopService/LoginResponse")]
        System.Threading.Tasks.Task<ClientApplication.BookshopServiceReference.User> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyBookshopService/Logout", ReplyAction="http://tempuri.org/IMyBookshopService/LogoutResponse")]
        bool Logout(ClientApplication.BookshopServiceReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyBookshopService/Logout", ReplyAction="http://tempuri.org/IMyBookshopService/LogoutResponse")]
        System.Threading.Tasks.Task<bool> LogoutAsync(ClientApplication.BookshopServiceReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyBookshopService/ListAll", ReplyAction="http://tempuri.org/IMyBookshopService/ListAllResponse")]
        ClientApplication.BookshopServiceReference.BookModel[] ListAll(ClientApplication.BookshopServiceReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyBookshopService/ListAll", ReplyAction="http://tempuri.org/IMyBookshopService/ListAllResponse")]
        System.Threading.Tasks.Task<ClientApplication.BookshopServiceReference.BookModel[]> ListAllAsync(ClientApplication.BookshopServiceReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyBookshopService/ListByIsbn", ReplyAction="http://tempuri.org/IMyBookshopService/ListByIsbnResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientApplication.BookshopServiceReference.ArgumentFault), Action="http://tempuri.org/IMyBookshopService/ListByIsbnArgumentFaultFault", Name="ArgumentFault", Namespace="http://schemas.datacontract.org/2004/07/BookshopDatabase")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientApplication.BookshopServiceReference.ArgumentNullFault), Action="http://tempuri.org/IMyBookshopService/ListByIsbnArgumentNullFaultFault", Name="ArgumentNullFault", Namespace="http://schemas.datacontract.org/2004/07/BookshopDatabase")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientApplication.BookshopServiceReference.IndexOutOfRangeFault), Action="http://tempuri.org/IMyBookshopService/ListByIsbnIndexOutOfRangeFaultFault", Name="IndexOutOfRangeFault", Namespace="http://schemas.datacontract.org/2004/07/BookshopDatabase")]
        ClientApplication.BookshopServiceReference.BookModel ListByIsbn(ClientApplication.BookshopServiceReference.User user, string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyBookshopService/ListByIsbn", ReplyAction="http://tempuri.org/IMyBookshopService/ListByIsbnResponse")]
        System.Threading.Tasks.Task<ClientApplication.BookshopServiceReference.BookModel> ListByIsbnAsync(ClientApplication.BookshopServiceReference.User user, string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyBookshopService/Insert", ReplyAction="http://tempuri.org/IMyBookshopService/InsertResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientApplication.BookshopServiceReference.ArgumentFault), Action="http://tempuri.org/IMyBookshopService/InsertArgumentFaultFault", Name="ArgumentFault", Namespace="http://schemas.datacontract.org/2004/07/BookshopDatabase")]
        bool Insert(ClientApplication.BookshopServiceReference.User user, string isbn, string title, string author, string publicationDate, int price, int instock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyBookshopService/Insert", ReplyAction="http://tempuri.org/IMyBookshopService/InsertResponse")]
        System.Threading.Tasks.Task<bool> InsertAsync(ClientApplication.BookshopServiceReference.User user, string isbn, string title, string author, string publicationDate, int price, int instock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyBookshopService/Update", ReplyAction="http://tempuri.org/IMyBookshopService/UpdateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientApplication.BookshopServiceReference.ArgumentFault), Action="http://tempuri.org/IMyBookshopService/UpdateArgumentFaultFault", Name="ArgumentFault", Namespace="http://schemas.datacontract.org/2004/07/BookshopDatabase")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientApplication.BookshopServiceReference.ArgumentNullFault), Action="http://tempuri.org/IMyBookshopService/UpdateArgumentNullFaultFault", Name="ArgumentNullFault", Namespace="http://schemas.datacontract.org/2004/07/BookshopDatabase")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientApplication.BookshopServiceReference.IndexOutOfRangeFault), Action="http://tempuri.org/IMyBookshopService/UpdateIndexOutOfRangeFaultFault", Name="IndexOutOfRangeFault", Namespace="http://schemas.datacontract.org/2004/07/BookshopDatabase")]
        bool Update(ClientApplication.BookshopServiceReference.User user, ClientApplication.BookshopServiceReference.BookModel bookModel, int price, int instock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyBookshopService/Update", ReplyAction="http://tempuri.org/IMyBookshopService/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(ClientApplication.BookshopServiceReference.User user, ClientApplication.BookshopServiceReference.BookModel bookModel, int price, int instock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyBookshopService/Delete", ReplyAction="http://tempuri.org/IMyBookshopService/DeleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientApplication.BookshopServiceReference.ArgumentFault), Action="http://tempuri.org/IMyBookshopService/DeleteArgumentFaultFault", Name="ArgumentFault", Namespace="http://schemas.datacontract.org/2004/07/BookshopDatabase")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientApplication.BookshopServiceReference.ArgumentNullFault), Action="http://tempuri.org/IMyBookshopService/DeleteArgumentNullFaultFault", Name="ArgumentNullFault", Namespace="http://schemas.datacontract.org/2004/07/BookshopDatabase")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientApplication.BookshopServiceReference.IndexOutOfRangeFault), Action="http://tempuri.org/IMyBookshopService/DeleteIndexOutOfRangeFaultFault", Name="IndexOutOfRangeFault", Namespace="http://schemas.datacontract.org/2004/07/BookshopDatabase")]
        bool Delete(ClientApplication.BookshopServiceReference.User user, string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyBookshopService/Delete", ReplyAction="http://tempuri.org/IMyBookshopService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(ClientApplication.BookshopServiceReference.User user, string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyBookshopService/DiscountAll", ReplyAction="http://tempuri.org/IMyBookshopService/DiscountAllResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientApplication.BookshopServiceReference.ArgumentFault), Action="http://tempuri.org/IMyBookshopService/DiscountAllArgumentFaultFault", Name="ArgumentFault", Namespace="http://schemas.datacontract.org/2004/07/BookshopDatabase")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientApplication.BookshopServiceReference.IndexOutOfRangeFault), Action="http://tempuri.org/IMyBookshopService/DiscountAllIndexOutOfRangeFaultFault", Name="IndexOutOfRangeFault", Namespace="http://schemas.datacontract.org/2004/07/BookshopDatabase")]
        bool DiscountAll(ClientApplication.BookshopServiceReference.User user, int pricePercentage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyBookshopService/DiscountAll", ReplyAction="http://tempuri.org/IMyBookshopService/DiscountAllResponse")]
        System.Threading.Tasks.Task<bool> DiscountAllAsync(ClientApplication.BookshopServiceReference.User user, int pricePercentage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyBookshopService/DiscountOne", ReplyAction="http://tempuri.org/IMyBookshopService/DiscountOneResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientApplication.BookshopServiceReference.ArgumentFault), Action="http://tempuri.org/IMyBookshopService/DiscountOneArgumentFaultFault", Name="ArgumentFault", Namespace="http://schemas.datacontract.org/2004/07/BookshopDatabase")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientApplication.BookshopServiceReference.ArgumentNullFault), Action="http://tempuri.org/IMyBookshopService/DiscountOneArgumentNullFaultFault", Name="ArgumentNullFault", Namespace="http://schemas.datacontract.org/2004/07/BookshopDatabase")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientApplication.BookshopServiceReference.IndexOutOfRangeFault), Action="http://tempuri.org/IMyBookshopService/DiscountOneIndexOutOfRangeFaultFault", Name="IndexOutOfRangeFault", Namespace="http://schemas.datacontract.org/2004/07/BookshopDatabase")]
        bool DiscountOne(ClientApplication.BookshopServiceReference.User user, string isbn, int pricePercentage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyBookshopService/DiscountOne", ReplyAction="http://tempuri.org/IMyBookshopService/DiscountOneResponse")]
        System.Threading.Tasks.Task<bool> DiscountOneAsync(ClientApplication.BookshopServiceReference.User user, string isbn, int pricePercentage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyBookshopService/DiscountByAuthor", ReplyAction="http://tempuri.org/IMyBookshopService/DiscountByAuthorResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientApplication.BookshopServiceReference.ArgumentFault), Action="http://tempuri.org/IMyBookshopService/DiscountByAuthorArgumentFaultFault", Name="ArgumentFault", Namespace="http://schemas.datacontract.org/2004/07/BookshopDatabase")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientApplication.BookshopServiceReference.ArgumentNullFault), Action="http://tempuri.org/IMyBookshopService/DiscountByAuthorArgumentNullFaultFault", Name="ArgumentNullFault", Namespace="http://schemas.datacontract.org/2004/07/BookshopDatabase")]
        bool DiscountByAuthor(ClientApplication.BookshopServiceReference.User user, string author, int pricePercentage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyBookshopService/DiscountByAuthor", ReplyAction="http://tempuri.org/IMyBookshopService/DiscountByAuthorResponse")]
        System.Threading.Tasks.Task<bool> DiscountByAuthorAsync(ClientApplication.BookshopServiceReference.User user, string author, int pricePercentage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyBookshopServiceChannel : ClientApplication.BookshopServiceReference.IMyBookshopService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyBookshopServiceClient : System.ServiceModel.ClientBase<ClientApplication.BookshopServiceReference.IMyBookshopService>, ClientApplication.BookshopServiceReference.IMyBookshopService {
        
        public MyBookshopServiceClient() {
        }
        
        public MyBookshopServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyBookshopServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyBookshopServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyBookshopServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClientApplication.BookshopServiceReference.User Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<ClientApplication.BookshopServiceReference.User> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public bool Logout(ClientApplication.BookshopServiceReference.User user) {
            return base.Channel.Logout(user);
        }
        
        public System.Threading.Tasks.Task<bool> LogoutAsync(ClientApplication.BookshopServiceReference.User user) {
            return base.Channel.LogoutAsync(user);
        }
        
        public ClientApplication.BookshopServiceReference.BookModel[] ListAll(ClientApplication.BookshopServiceReference.User user) {
            return base.Channel.ListAll(user);
        }
        
        public System.Threading.Tasks.Task<ClientApplication.BookshopServiceReference.BookModel[]> ListAllAsync(ClientApplication.BookshopServiceReference.User user) {
            return base.Channel.ListAllAsync(user);
        }
        
        public ClientApplication.BookshopServiceReference.BookModel ListByIsbn(ClientApplication.BookshopServiceReference.User user, string isbn) {
            return base.Channel.ListByIsbn(user, isbn);
        }
        
        public System.Threading.Tasks.Task<ClientApplication.BookshopServiceReference.BookModel> ListByIsbnAsync(ClientApplication.BookshopServiceReference.User user, string isbn) {
            return base.Channel.ListByIsbnAsync(user, isbn);
        }
        
        public bool Insert(ClientApplication.BookshopServiceReference.User user, string isbn, string title, string author, string publicationDate, int price, int instock) {
            return base.Channel.Insert(user, isbn, title, author, publicationDate, price, instock);
        }
        
        public System.Threading.Tasks.Task<bool> InsertAsync(ClientApplication.BookshopServiceReference.User user, string isbn, string title, string author, string publicationDate, int price, int instock) {
            return base.Channel.InsertAsync(user, isbn, title, author, publicationDate, price, instock);
        }
        
        public bool Update(ClientApplication.BookshopServiceReference.User user, ClientApplication.BookshopServiceReference.BookModel bookModel, int price, int instock) {
            return base.Channel.Update(user, bookModel, price, instock);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(ClientApplication.BookshopServiceReference.User user, ClientApplication.BookshopServiceReference.BookModel bookModel, int price, int instock) {
            return base.Channel.UpdateAsync(user, bookModel, price, instock);
        }
        
        public bool Delete(ClientApplication.BookshopServiceReference.User user, string isbn) {
            return base.Channel.Delete(user, isbn);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(ClientApplication.BookshopServiceReference.User user, string isbn) {
            return base.Channel.DeleteAsync(user, isbn);
        }
        
        public bool DiscountAll(ClientApplication.BookshopServiceReference.User user, int pricePercentage) {
            return base.Channel.DiscountAll(user, pricePercentage);
        }
        
        public System.Threading.Tasks.Task<bool> DiscountAllAsync(ClientApplication.BookshopServiceReference.User user, int pricePercentage) {
            return base.Channel.DiscountAllAsync(user, pricePercentage);
        }
        
        public bool DiscountOne(ClientApplication.BookshopServiceReference.User user, string isbn, int pricePercentage) {
            return base.Channel.DiscountOne(user, isbn, pricePercentage);
        }
        
        public System.Threading.Tasks.Task<bool> DiscountOneAsync(ClientApplication.BookshopServiceReference.User user, string isbn, int pricePercentage) {
            return base.Channel.DiscountOneAsync(user, isbn, pricePercentage);
        }
        
        public bool DiscountByAuthor(ClientApplication.BookshopServiceReference.User user, string author, int pricePercentage) {
            return base.Channel.DiscountByAuthor(user, author, pricePercentage);
        }
        
        public System.Threading.Tasks.Task<bool> DiscountByAuthorAsync(ClientApplication.BookshopServiceReference.User user, string author, int pricePercentage) {
            return base.Channel.DiscountByAuthorAsync(user, author, pricePercentage);
        }
    }
}
